### ISSUE TITLE
Courses not adding

### ISSUE THREAD

**Issue by paulbert** [ole-vi/planet#102]
In the current courses component isn't adding courses, the PUT request is returning with a 403 error.  Could be an issue with having an admin on the CouchDB.

**Comment by ajGingrich** [comment]
It seems to work fine for me now. Not sure if I was the only one having this problem, but I am going to go ahead and close.

**Comment by ajGingrich** [comment]
sorry, error again...

**Comment by ajGingrich** [comment]
The form submits fine except for when *End Date* is selected. I can't find the source of the problem but I think it is in the `endDateValidator`
