### ISSUE TITLE
Update meetupadds to use dash notation

### ISSUE THREAD

**Issue by paulbert** [ole-vi/planet#108]
I plan to add a PR for this later today, but in case someone sees this earlier feel free to go ahead and fix this.

I'd like to switch the Meetups add file name & class name to follow the Angular suggested style here:
https://angular.io/guide/styleguide#separate-file-names-with-dots-and-dashes

So `meetupsadd.component.ts` will become `meetups-add.component.ts` (and same for the spec file) and `MeetupsaddComponent` will become `MeetupsAddComponent`

**Comment by kigsmtua** [comment]
@paulbert issue fixed in #109
