### ISSUE TITLE
There are some errors in custom-validator.ts and course-validator.service.ts when running ng test

### ISSUE THREAD

**Issue by lucy811** [ole-vi/planet#110]
When I run ng test, there are some errors.
<img width="986" alt="errors" src="https://user-images.githubusercontent.com/25615945/31869537-584fff94-b76e-11e7-85ae-2506eb502b51.png">
Could anyone check it?

**Comment by LKhadka** [comment]
Are you importing the rxjs operator from [here](https://github.com/ole-vi/planet/blob/master/src/app/shared/rxjs-imports.ts)?

**Comment by lucy811** [comment]
I tried to add "import '.share/rxjs-imports.ts';" in the course-validator.service.spec.ts , the errors still exist.

**Comment by LKhadka** [comment]
I think it will work if you import it in the `app.component.spec.ts`

**Comment by lucy811** [comment]
@LKhadka Thank you . I have tried it . No errors now.

**Comment by LKhadka** [comment]
No problem @lucy811. @paulbert  Do you think a PR should be made to import the rxjs operators to `app.component.spec.ts`?

**Comment by lucy811** [comment]
@LKhadka @paulbert I can make a PR for this. Thanks
