### ISSUE TITLE
Add Course Components

### ISSUE THREAD

**Issue by ajGingrich** [ole-vi/planet#119]
Course subcomponents need to be added. There are placeholder buttons in the course component so you can see which ones are needed. These will be Open, Manage, View Course, Credits, and Progress. In addition, Request Course needs to be developed although there is already a component. Here are a few relevant screenshots from Bell-Apps:

#### Course Component
![courses-component](https://user-images.githubusercontent.com/22775484/31964869-ba63a654-b8c2-11e7-81b7-d4a5f6f4732f.png)

#### Request
![courses-component-request](https://user-images.githubusercontent.com/22775484/31964971-08964b88-b8c3-11e7-98e8-9c60262fd36a.png)

#### Open
![course-component-open](https://user-images.githubusercontent.com/22775484/31964879-c1eeec3a-b8c2-11e7-8776-f287cd3d8406.png)

#### Manage
![course-component-manage](https://user-images.githubusercontent.com/22775484/31964893-c89036ca-b8c2-11e7-8fe4-a363c83b409d.png)

#### View
![course-component-view](https://user-images.githubusercontent.com/22775484/31964902-ce266104-b8c2-11e7-8a3e-4f87df207663.png)

**Comment by amanuely** [comment]
@ajGingrich I can look at this and work on if it is still open

**Comment by ajGingrich** [comment]
@amanuely great thanks. I would wait until https://github.com/ole-vi/planet/pull/107 is merged though

**Comment by razu9861** [comment]
Outdated
