### ISSUE TITLE
Nation configuration/setting

### ISSUE THREAD

**Issue by Rupesh87** [ole-vi/planet#126]
![ssas.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5860f49dee006e0e0082488f/125516c66e82c728ace21e0d46fb879b30c0cfeb9ffbb049a15ee4d67304722a2d50a62826d3e27eb91b29505f5f4cfa150e0a40fdfd9b37b4f46d2ede0356b49b381d66cc2f10abb2831abe01bf248e4683b2bc8b4ed2a5.png)

**Comment by Pr0chin** [comment]
- [ ] http://192.168.10.111:5982/apps/_design/bell/MyApp/index.html#configuration/add

**Comment by Pr0chin** [comment]
Repeated Issue of #157
