### ISSUE TITLE
Nation : Clicking nation name shows config of nation

### ISSUE THREAD

**Issue by Pr0chin** [ole-vi/planet#157]
![nat2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5860f49dee006e0e0082488f/125516c66e82c728ace21e0d46e6958e71c0cfeb9ffbb049a15ee4d67304722a2d50a62826d3e27eb91b29505f5f4cfa150e0a40fdfd9b37b4f46d2ede0356b49b381d66cc2f10abb2831abe01bf24824b87b4b48944d2a5.png)

**Comment by Pr0chin** [comment]
- [ ] http://192.168.10.111:5982/apps/_design/bell/MyApp/index.html#configuration/add
- [ ] view should as same as above given snap shot.
- [ ] Data should be render in a configuration's field.

**Comment by nirojdyola** [comment]
Data has been fetched from the relative nation and This is repeated issuw which has been done in issue number #162
