### ISSUE TITLE
Add resource component

### ISSUE THREAD

**Issue by paulbert** [ole-vi/planet#16]
The resource component will need to be implemented in a few steps.  Let's start with the form so we can populate a resources database.  It should:

* Add a document to the database with the form fields found in the current BeLL-Apps on a form submit click with the exception of the attachment
* Not add a document if a resource with the same title currently exists
* Be linked to from the `LIBRARY` nav link

Notes:
* Adding attachments to CouchDB adds a little more complexity to this than needed.  Let's get the form working, then at a later time we can implement the attachments.
* Here's an image of the current form for reference:
![Current BeLL resource form](http://open-learning-exchange.github.io/pages/uploads/images/htmlresources.png)

**Comment by nirojdyola** [comment]
1. Attachment (tested in mozilla and chrome)
   Tested files : image, pdf, docs, excel,audio

![resources](https://user-images.githubusercontent.com/7495421/30018770-e36d8874-917d-11e7-9873-729a27273114.png)

Note : Other fields need to add.
@razu9861 over to you .
