### ISSUE TITLE
Code Climate integration

### ISSUE THREAD

**Issue by mappuji** [ole-vi/planet#168]
To make us diligent to re-check our code lets have code climate in our system. What do you guys think?

**Comment by paulbert** [comment]
I like the idea.  It looks like Code Climate has TypeScript support in beta, though, and these two options have official support for TypeScript listed on their homepage:
https://codebeat.co/
https://houndci.com/

**Comment by mappuji** [comment]
Let us do some little research about those three options and choose which one to implement.

**Comment by mappuji** [comment]
https://codeclimate.com/github/ole-vi/planet
