### ISSUE TITLE
Add courses component

### ISSUE THREAD

**Issue by paulbert** [ole-vi/planet#17]
The courses component will need to be implemented in a few steps. Let's start with the form so we can populate a courses database. It should:

* Add a document to the database with the form fields found in the current BeLL-Apps on a form submit click with the exception of the attachment
* Not add a document if a resource with the same title currently exists
* Be linked to from the `COURSES` nav link

Notes:
* No need to bother with the real text editor, you can just use a plain textbox description for now.

**Comment by paulbert** [comment]
For reference, here's the current add courses form:
![addcourse](https://user-images.githubusercontent.com/9203229/29848545-5ee77138-8cef-11e7-95b3-e733bf8c0840.png)

**Comment by paulbert** [comment]
**courses.component.ts**
* I'd put the form options on lines 26-53 into a separate file at this point.  This file is a little large, and I don't think those defaults will change as much as the form methods.
* I'd rather we didn't add then delete a resource if the title is a duplicate.  I like the use of CouchDB design docs, and I imagine there's a solution there which would solve this.  Alternatively, you can query the database with [/_find](http://docs.couchdb.org/en/2.1.0/api/database/find.html#selector-basics) and don't add the document if there is a result.  Either way, we wouldn't need to use the `courses-checker.json` as well.
* You don't need an ngOnInit to initialize the form values.  You can just do that in createForm.
* For the `toggleWeekly()` method I think it would be simpler to loop once through the **day** `formArray` and remove each value that had been pushed.

**courses.component.html**
* The cancel button should be of `type="button"` rather than `type="submit"` so it does not run the `onSubmit` code when clicked.

**custom-validators.ts**
* First, I don't think is needed since the input `type="number"` limits it to a number and we can use the built in `min` validator [(see here)](https://angular.io/api/forms/Validators) to make sure it is a positive number.
* This also throws an error since the value is actually stored as a number and the `.match` method is only a method of strings.  This error seems to be breaking the `cancel()` method.

**CouchDB design docs**
* I think these should go into a different folder, maybe called `design`

**Comment by LKhadka** [comment]
I have fixed most of the issues you talked about. Now, I need to work on validators.
