### ISSUE TITLE
Auto login on registration

### ISSUE THREAD

**Issue by paulbert** [ole-vi/planet#18]
Currently when a user is added the login page is reloaded.  Modify the login.component.ts to create a session when the user is added.

**Comment by nirojdyola** [comment]
@paulbert 
But , if the user is already logged in and he/she added the user , then it"ll replace the session of current one and logged in with the created user one,

**Comment by paulbert** [comment]
@dogi @lmmrssa @leonardmensah Are we going to need functionality for users to be able to create other users while they are logged in to the Planet app?  Or will people only be creating their own profile?

**Comment by lmmrssa** [comment]
@paulbert probably not required to create other account but there will be need to promote the role or inactive etc.
