### ISSUE TITLE
Login redirect not working

### ISSUE THREAD

**Issue by paulbert** [ole-vi/planet#19]
I had implemented the AuthGuard based on [this tutorial](http://jasonwatmore.com/post/2016/12/08/angular-2-redirect-to-previous-url-after-login-with-auth-guard) to include functionality to save the route the user requests in the query string and then redirect to that page after login.

Currently that's not working as intended, so needs fixing.

**Comment by nirojdyola** [comment]
1 .Login Page (stateURL = meetups)
![loginurl](https://user-images.githubusercontent.com/7495421/29909504-e767e158-8e45-11e7-8cb5-86582cf1eed6.png)

2. Meetups after login page
![meetups](https://user-images.githubusercontent.com/7495421/29909506-eae5c5d4-8e45-11e7-9681-844265684753.png)

Here, 1. checking meetups before login as shown . and 2. redirect to meetups page after login as it needs to maintain the state.
