### ISSUE TITLE
There are some errors when running ng test

### ISSUE THREAD

**Issue by lucy811** [ole-vi/planet#276]
When I run ng test, there are some errors.
<img width="1039" alt="unit_test_errors" src="https://user-images.githubusercontent.com/25615945/34363393-5a2aecce-ea41-11e7-927e-7b0dbee4b69a.png">

I have synchronized my pull request branch with the master branch, and I have tried to add "import { Observable } from 'rxjs/Observable';
import { debugOperator } from '../../debug-operator’;” in nation.component.spec.ts and app.component.spec.ts, but the errors still exist.

Besides, I have tried ng test in the latest master branch, the errors also exist.

**Comment by paulbert** [comment]
Thanks for bringing this up, Lucy!

For everyone else: this is fixed as part of the open PR #237.  Once that is merged we can close this issue.

**Comment by paulbert** [comment]
Now that #237 is merged, closing this.
