### ISSUE TITLE
Login name must be unique between admin and user

### ISSUE THREAD

**Issue by Rupesh87** [ole-vi/planet#284]

**Comment by lmmrssa** [comment]
Users are saved in _users table and Admin under _config, so username is made unique only for _users table. We need to make it unique across both

**Comment by paulbert** [comment]
An option is when we create an admin to also create a user with the same credentials.  I just did a little test run with this and I was still able to login as an admin in the utilities and the app.

This would also solve the issue of giving admins a profile.
