### ISSUE TITLE
Build in arm vs in x86 not consistent

### ISSUE THREAD

**Issue by mappuji** [ole-vi/planet#305]
Problem
* When build in x86 fails, the travis is not red
* When build in x86 fails, build in arm still uploading new latest which is false (it only repush the old images)

Solution:
* need to debug build pipeline and build script

Examples:

<img width="945" alt="screen shot 2018-01-10 at 9 38 14 am" src="https://user-images.githubusercontent.com/11813607/34753348-0fab242a-f5ea-11e7-8c50-92d8f6067f44.png">

<img width="925" alt="screen shot 2018-01-10 at 9 39 04 am" src="https://user-images.githubusercontent.com/11813607/34753375-2d0a6a44-f5ea-11e7-9ce7-17dd4784dfc8.png">

**Comment by dogi** [comment]
found out same thing yesterday

**Comment by mappuji** [comment]
We will upgrade stuff when we use travis stage

**Comment by mappuji** [comment]
Done in #503
