### ISSUE TITLE
Password(type="password")

### ISSUE THREAD

**Issue by nirojdyola** [ole-vi/planet#34]
If you check in login and register , you find type="text" for password, So I think it needs to be change,
![loginurl](https://user-images.githubusercontent.com/7495421/30198453-84442ad4-948d-11e7-8e5e-7f3573e5ec6c.png)

**Comment by razu9861** [comment]
![screen shot 2017-09-08 at 12 23 02 pm](https://user-images.githubusercontent.com/24647983/30199023-92aa4c90-9490-11e7-915c-3872fe0a1cb4.png)
![screen shot 2017-09-08 at 12 17 08 pm](https://user-images.githubusercontent.com/24647983/30199079-c05f4334-9490-11e7-868f-96658423bace.png)
