### ISSUE TITLE
Dashboard View

### ISSUE THREAD

**Issue by lmmrssa** [ole-vi/planet#352]
Start filling dashboard view
- [x] Add the center block with different blocks

**Comment by nirojdyola** [comment]
![Dashboard V4Dashboard V2.4.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58aeb9eb257d931a000df4b2/125516c66e82c728ace21e0d46cc95892b808ca89dedff75f079f187214428723b00e31d22cbb76af3006b1300051bff054a5556f9f0dd2ff3e53a76db5a5de4d36c5f74c46b45faed861ebb13a632c91edbe2e3d7158abd7f37ed998d4f341f00198ff75830a69d4dc051f359ac.jpg)

Should have 4 blocksas shown in image.
Let's focus on design now.
