### ISSUE TITLE
Access restricted to admins

### ISSUE THREAD

**Issue by nirojdyola** [ole-vi/planet#388]
![screen shot 2018-02-09 at 12 39 56 pm](https://user-images.githubusercontent.com/7495421/36015553-d280f0c2-0d66-11e8-99e0-6d167812ba4b.png)
On the first setup that means admin is also restricted on viewing users. Please fix the issue.

**Comment by lmmrssa** [comment]
It looks like its not getting the admin user copy being created on the first instance. But later on it seems to work. So need to look further on getuser
