### ISSUE TITLE
Star Rating design 

### ISSUE THREAD

**Issue by nirojdyola** [ole-vi/planet#409]
Works fine in Chrome, but not in mozilla. Some circle is displaying over star.
And also when I click upto 5 star, it is not displaying at all.
![screen shot 2018-02-15 at 2 51 16 pm](https://user-images.githubusercontent.com/7495421/36248527-bbee18d0-122f-11e8-8144-5c6636598e91.png)

**Comment by paulbert** [comment]
The problem is the `display: inline` that was necessary to make sure the yellow stars overlapped is causing Firefox to render the incorrect icon, with incorrect sizing and spacing.

This isn't newbie friendly.  The cause of this odd behavior is unclear and the solution will not be simple.
