### ISSUE TITLE
Versioning for planet

### ISSUE THREAD

**Issue by mappuji** [ole-vi/planet#44]
We need a versioning an convention who saved in `package.json` of our npm package.

This is my proposal `planet-{{version}}-{{commit_id}}`

only `version` included in `package.json` the `commit_id` is only for artifact (docker) name.

**Comment by mappuji** [comment]
It is hard to have a good versioning model if we only have master. It is better I think to have two main branch `development` and `master`, `development` is our current effort to develop stuff then `master` is our stable release version. So whenever there is a pull request we add to `development` then to `master`.

I know that for small open source project it is not common to use that branching model, but what do you think?

Here is the reference http://nvie.com/posts/a-successful-git-branching-model/

**Comment by lmmrssa** [comment]
i'm not sure about adding commit_id in the version number

**Comment by mappuji** [comment]
I am doing in docker like this

* https://hub.docker.com/r/treehouses/planet/tags/ --> production
* https://hub.docker.com/r/treehouses/planet-dev/tags/ --> development

**Comment by mappuji** [comment]
hi @lmmrssa and @paulbert this idea pops up again in my mind, can what do you think about start using versioning in our release?

cc: @dogi

**Comment by dogi** [comment]
@mappuji like your suggestion

@lmmrssa @mappuji @paulbert wonder mostly where we would save changelog ;)

**Comment by mappuji** [comment]
Already implemented
