### ISSUE TITLE
admin user is kinda not getting any data ...

### ISSUE THREAD

**Issue by dogi** [ole-vi/planet#454]
![screen shot 2018-02-28 at 1 15 26 am](https://user-images.githubusercontent.com/13684059/36772896-15a22c82-1c25-11e8-8eb9-ab04a33f3806.png)

**Comment by paulbert** [comment]
Do you mean that the information inputted during configuration does not get added to the admin profile?  If so, then yes I agree this is an issue that should be fixed.  First, Middle, Last Name, Email, & Phone Number should all be populated from the configuration.

![login_configuration](https://user-images.githubusercontent.com/9203229/36798266-2a41ef80-1c78-11e8-94e9-61c608082dab.png)

**Comment by paulbert** [comment]
Reopening.  The commit is only working when a role has been deleted using the "X" in the pill.

**Comment by paulbert** [comment]
Hmm...I think I reopened the wrong issue based on that last comment.  Closing.
