### ISSUE TITLE
Multiple selection value in Resource form is string instead of array (for previously saved resources in DB)

### ISSUE THREAD

**Issue by adepojubosun** [ole-vi/planet#531]
![screenshot from 2018-03-19 10-53-19](https://user-images.githubusercontent.com/7988475/37603788-c6b05a18-2b65-11e8-9efd-5152cc7f7ace.png)

![screenshot from 2018-03-19 11-33-04](https://user-images.githubusercontent.com/7988475/37605572-da9279cc-2b69-11e8-9a60-794e17334e5d.png)

**_Error: Value must be an array in multiple-selection mode_**
This error is thrown if you attempt to assign a value other than null, undefined, or an array to a <mat-select multiple>. 

Default resources in database need clarification. All multiple selection values in the database are string values instead of array. 
This issue is required to complete issue #498

**Comment by paulbert** [comment]
Good catch, we should change this in the mock data in /design/resources

**Comment by lmmrssa** [comment]
change "resourceFor": "Learner" to array
