### ISSUE TITLE
Activity Report

### ISSUE THREAD

**Issue by nirojdyola** [ole-vi/planet#595]
![screen shot 2018-04-09 at 10 50 06 am](https://user-images.githubusercontent.com/7495421/38481020-4cd2a184-3bb8-11e8-9267-42e829f84fd9.png)

**Comment by lmmrssa** [comment]
this issue is of BellApps so why is it on planet?

**Comment by razu9861** [comment]
Closing this issue because right now we don’t have enough data and logs, we can reopen this issue once all logs and data are available from nation and communities
