### ISSUE TITLE
The left navbar, looks like home always selected

### ISSUE THREAD

**Issue by Tille88** [ole-vi/planet#628]
Current design of navbar, with the home selector with white fill makes it appear to be always the currently chosen one to first time users (or at least first time I used it).

<img width="241" alt="screen shot 2018-04-07 at 22 07 59" src="https://user-images.githubusercontent.com/16757941/38667970-223536c8-3e6d-11e8-8ed4-fc6f91810d95.png">

**Comment by razu9861** [comment]
@Tille88 home icon is material icon and other icons are svg icon thats why it is more highleted in color, once Ux team create new svg icon for home we can replace it.

**Comment by Tille88** [comment]
@razu9861 Makes sense :) Let me know if this should be left open until this is done or how you usually deal with this
