### ISSUE TITLE
New user photo upload not resized

### ISSUE THREAD

**Issue by Tille88** [ole-vi/planet#634]
When creating a new user, only when picking a small photo it seems to make sense size-wise.
When uploading a large image it takes up the full screen as seen below. Rescaling to something consistent but small may make sense in this case.

<img width="701" alt="screen shot 2018-04-12 at 16 55 07" src="https://user-images.githubusercontent.com/16757941/38670206-51617d9e-3e72-11e8-8bff-dd819da9a225.png">

**Comment by paulbert** [comment]
Looking into an image crop & resize tool because we also would like square dimensions. PR #598

**Comment by ArashDai** [comment]
PR #692
