### ISSUE TITLE
Course time stored as text, should be Date

### ISSUE THREAD

**Issue by paulbert** [ole-vi/planet#638]
If we store the time as a JavaScript Date, we can use the Angular date pipe which according to the documentation will automatically localize the format of the time shown.

**Comment by BasnetSamriddhi** [comment]
![coursedate](https://user-images.githubusercontent.com/35338384/38791412-38bc5a5a-4167-11e8-961b-407f866b2ead.png)

The course date section is not there in the new layout, I am not clear about this issue.

**Comment by paulbert** [comment]
We decided to move those fields after I wrote this issue. Closing because it is no longer needed.
