### ISSUE TITLE
user._attachments for images has key of "undefined"

### ISSUE THREAD

**Issue by Tille88** [ole-vi/planet#645]
src/app/home/home.component.ts

In userImageSrc() function, this.user._attachments has a key of undefined.
> {
    "undefined": {
        "content_type": "application/octet-stream",
        "revpos": 46,
        "digest": "md5-mymRZJxcXnBLE62ZYIIK2A==",
        "length": 9809,
        "stub": true
    }
}

Meaning that the image src ends up being something along the lines of:
> http://127.0.0.1:2200/_users/org.couchdb.user:test/undefined

**Comment by paulbert** [comment]
Have you seen this occur on the master branch or just on #598 ?  I have only seen it on that branch and I think it's related to the change to use `ngx-img`

**Comment by Tille88** [comment]
@paulbert Oh sorry, that was sloppy of me. Yes, I was on the https://github.com/ole-vi/planet/pull/598 branch when I found that issue, should have kept it in that PR. Will probably not have time before Thursday to look into this more, but will keep changes and close this issue here if that is the case.
