### ISSUE TITLE
Server Side Rendering/Angular Universal?

### ISSUE THREAD

**Issue by LKhadka** [ole-vi/planet#75]
I was wondering if we would be including [angular universal](https://universal.angular.io) to bell apps? It could help increase the perceived performance and since we will have to use node.js for that we could also abstract away CouchDB.

**Comment by paulbert** [comment]
Thanks for posting this.  My initial thought is that this won't be a priority since we're more working towards having the app cached on the client to be usable while fully offline.

Good to discuss for tomorrow, though.

**Comment by LKhadka** [comment]
Ah I see. I guess we would not need to be concerned about it for now since It would be an unnecessary overhead. Closing this for now.
