### ISSUE TITLE
Add courses list view

### ISSUE THREAD

**Issue by paulbert** [ole-vi/planet#83]
Similar to #82, the courses link should land on a list of available courses with buttons to manage the course.  I'll try to get a screenshot of the design for you to work off of, but in the meantime something similar to the current BeLL-apps will be OK.

For the scope of this issue, please just add HTML & TypeScript code for this.  I'd like broader CSS for tables to be used, and have included that as a separate issue #17.  That being said, coordinating development with the work on the CSS to incorporate that into this PR would be great!

**Comment by ajGingrich** [comment]
I see that someone has already developed part of a courses component but router link doesn't
 work to check it out. What am I missing?

![courses-link1](https://user-images.githubusercontent.com/22775484/31678459-7d569f42-b32b-11e7-9cb5-7062f224ea11.png)

![courses-link2](https://user-images.githubusercontent.com/22775484/31678471-872f9d20-b32b-11e7-9962-dc3a0cfcd2a9.png)
